parameters:
#    relhub_web.example.class: Relhub\WebBundle\Example

services:
#    relhub_web.example:
#        class: %relhub_web.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
