parameters:
#    relhub_web.example.class: Relhub\WebBundle\Example

services:
    relhub_web.release_version:
        class: Relhub\WebBundle\Service\ReleaseVersionService
        arguments: [@doctrine.orm.entity_manager, @relhub_build.build]
