parameters:
#    relhub_build.example.class: Relhub\BuildBundle\Example

services:
#    relhub_build.example:
#        class: %relhub_build.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
