Relhub\WebBundle\Entity\Project:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        actions:
            type: text
        options:
            type: text

    lifecycleCallbacks: {  }

    manyToMany:
        users:
          targetEntity: User
          joinTable:
            name: UserProjects
            joinColumns:
              user_id:
                referencedColumnName: id
            inverseJoinColumns:
              project_id:
                referencedColumnName: id
