Relhub\WebBundle\Entity\User:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255

        usernameCanonical:
            type: string
            length: 255

        email:
            type: string
            length: 255

        emailCanonical:
            type: string
            length: 255


        password:
            type: string
            length: 255
        salt:
            type: string
            length: 255

    lifecycleCallbacks: {  }


