Relhub\WebBundle\Entity\WorkflowState:
    type: entity
    table: null
    repositoryClass: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        ordering:
            type: integer


    lifecycleCallbacks: {  }

    manyToOne:
        project:
            targetEntity: Project
            inversedBy: project
            joinColumn:
                name: project_id
                referencedColumnName: id




