check:
 - /var/docroot/release-hub/bin/createBranch.sh {{ checkout }} {{ releaseBranch }} {{ remote }} 
 - /var/docroot/release-hub/bin/merge.sh {{ checkout }} {{ branch }} {{ releaseBranch }} {{ remote }} --dry:
   - each branch
 - test feature branches
 - check ticket status
 - extra something
release:
 - create release branch
 - merge feature branches
 - deploy release branch to test
 - sync dbs and files from prod to test
 - notifications
regression:
 - regression test release  
publish:
